#rank
quartz:
#add the commands you would like to add to the ranks. 
-  "Commands and features for the &f[&7Quartz&f] rank:"
-  "&3/v w &f- &4Virtual Workbench."
-  "&3/v uc &f- &4Uncrafter."
-  "&3/tpa <player> &f- &4Teleport to a player"
-  "&3/sethome <name> &f- &4Set home. &5(up to 2 homes)"
-  "&3/home <name> &f- &4Go to homes."
-  "&3/hat &f- &4Get a block as head gear &5(the block in your hand becomes your head. gear)"
-  "&3Always join the server, &4Even when full!"
-  "&3Make use of pets!!"
-  "&3Make use of XP banks"
-  "&3Get special donation quests!"

redstone:
-  "Commands and features for the &f[&cRedstone&f] rank:"
-  "&3/v w &f- &4Virtual Workbench."
-  "&3/v uc &f- &4Uncrafter."
-  "&3/v c &f- &4Virtual Chest &5(Drops on death)"
-  "&3/v f &f- &4Virtual Furnace"
-  "&3/tpa <player> &f- &4Teleport to a player"
-  "&3/sethome <name> &f- &4Set home. &5(up to 3 homes)"
-  "&3/home <name> &f- &4Go to homes."
-  "&3/hat &f- &4Get a block as head gear &5(the block in your hand becomes your head. gear)"
-  "&3Always join the server, &4Even when full!"
-  "&3Make use of pets!!"
-  "&3Make use of XP banks"
-  "&3Get special donation quests!"

lapis:
-  "Commands and features for the &f[&9Lapis&f] rank:"
-  "&3/v w &f- &4Virtual Workbench."
-  "&3/v uc &f- &4Uncrafter."
-  "&3/v c &f- &4Virtual Chest &5(keep on death)"
-  "&3/v e &f- &4Virtual Echantment Table &5(With max amount of books(Currently bugged)"
-  "&3/v f &f- &4Virtual Furnace"
-  "&3/tpa <player> &f- &4Teleport to a player"
-  "&3/sethome <name> &f- &4Set home. &5(up to 4 homes)"
-  "&3/home <name> &f- &4Go to homes."
-  "&3/deathtp &f- &4Return to death point &5(costs 10 Bottlecaps per use)"
-  "&3/hat &f- &4Get a block as head gear &5(the block in your hand becomes your head. gear)"
-  "&3Always join the server, &4Even when full!"
-  "&3Make use of pets!!"
-  "&3Make use of XP banks"
-  "&3Get special donation quests!"

diamond:
-  "Commands and features for the &f[&3Diamond&f] rank:"
-  "&3/v w &f- &4Virtual Workbench."
-  "&3/v uc &f- &4Uncrafter."
-  "&3/v c &f- &4Virtual Chest &5(keep on death)"
-  "&3/v e &f- &4Virtual Echantment Table &5(With max amount of books(Currently bugged))"
-  "&3/v b &f- &4Virtual Brewing Stand"
-  "&3/v f &f- &4Virtual Furnace"
-  "&3/v a &f- &4Virtual Anvil"
-  "&3/tpa <player> &f- &4Teleport to a player"
-  "&3/sethome <name> &f- &4Set home. &5(up to 5 homes)"
-  "&3/home <name> &f- &4Go to homes."
-  "&3/deathtp &f- &4Return to death point &5(costs 10 Bottlecaps per use)"
-  "&3/hat &f- &4Get a block as head gear &5(the block in your hand becomes your head. gear)"
-  "&3Always join the server, Even when full!"
-  "&3Make use of pets!!"
-  "&3Make use of XP banks"
-  "&3Get special donation quests!"

ender:
-  "Commands and features for the &f[&5Ender&f] rank:"
-  "&3/v w &f- &4Virtual Workbench."
-  "&3/v uc &f- &4Uncrafter."
-  "&3/v c &f- &4Virtual Chest &5(keep on death)"
-  "&3/v e &f- &4Virtual Echantment Table &5(With max amount of books(Currently bugged))"
-  "&3/v b &f- &4Virtual Brewing Stand"
-  "&3/v f &f- &4Virtual Furnace"
-  "&3/v a &f- &4Virtual Anvil"
-  "&3/tpa <player> &f- &4Teleport to a player"
-  "&3/sethome <name> &f- &4Set home. &5(up to 5 homes)"
-  "&3/home <name> &f- &4Go to homes."
-  "&3/deathtp &f- &4Return to death point &5(costs 10 Bottlecaps per use)"
-  "&3/hat &f- &4Get a block as head gear &5(the block in your hand becomes your head. gear)"
-  "&3Always join the server, Even when full!"
-  "&3Make use of pets!!"
-  "&3Make use of XP banks"
-  "&3Get special donation quests!"
